Make deb scripts more compliant with Debian policy

diff --git a/pkg/debian/salt-api.postinst b/pkg/debian/salt-api.postinst
--- a/pkg/debian/salt-api.postinst
+++ b/pkg/debian/salt-api.postinst
@@ -1,37 +1,47 @@
 #!/bin/sh
+# postinst script for salt-api
+#
+# See: dh_installdeb(1).
 
-. /usr/share/debconf/confmodule
+set -e
+
+# Summary of how this script can be called:
+#        * <postinst> 'configure' <most-recently-configured-version>
+#        * <old-postinst> 'abort-upgrade' <new version>
+#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
+#          <new-version>
+#        * <postinst> 'abort-remove'
+#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
+#          <failed-install-package> <version> 'removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package.
 
 case "$1" in
   configure)
-    db_get salt-api/user
-    if [ "$RET" != "root" ]; then
-      if [ ! -e "/var/log/salt/api" ]; then
-        touch /var/log/salt/api
-        chmod 640 /var/log/salt/api
-      fi
-      chown $RET:$RET /var/log/salt/api
-    fi
-    if command -v systemctl; then
-        db_get salt-api/active
-        RESLT=$(echo "$RET" | cut -d ' ' -f 1)
-        if [ "$RESLT" != 10 ]; then
-            systemctl daemon-reload
-            if [ "$RESLT" = "active" ]; then
-                systemctl restart salt-api
-            fi
-            db_get salt-api/enabled
-            RESLT=$(echo "$RET" | cut -d ' ' -f 1)
-            if [ "$RESLT" = "disabled" ]; then
-                systemctl disable salt-api
-            else
-                systemctl enable salt-api
-            fi
-        else
-            systemctl daemon-reload
-            systemctl restart salt-api
-            systemctl enable salt-api
+    . /usr/share/debconf/confmodule
+    if db_get salt-api/user; then
+      if [ "$RET" != "root" ]; then
+        if [ ! -e "/var/log/salt/api" ]; then
+          touch /var/log/salt/api
+          chmod 640 /var/log/salt/api
         fi
+        chown $RET:$RET /var/log/salt/api
+      fi
     fi
   ;;
+  abort-upgrade|abort-remove|abort-deconfigure)
+  ;;
+
+  *)
+    echo "postinst called with unknown argument '$1'" >&2
+    exit 1
+  ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
