Make deb scripts more compliant with Debian policy

diff --git a/pkg/debian/salt-minion.postinst b/pkg/debian/salt-minion.postinst
--- a/pkg/debian/salt-minion.postinst
+++ b/pkg/debian/salt-minion.postinst
@@ -1,41 +1,57 @@
 #!/bin/sh
+# postinst script for salt-minion.
+#
+# see: dh_installdeb(1)
 
-. /usr/share/debconf/confmodule
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 case "$1" in
   configure)
-    db_get salt-minion/user
-    if [ "$RET" != "root" ]; then
-      if [ ! -e "/var/log/salt/minion" ]; then
-        touch /var/log/salt/minion
-        chmod 640 /var/log/salt/minion
-      fi
-      if [ ! -e "/var/log/salt/key" ]; then
-        touch /var/log/salt/key
-        chmod 640 /var/log/salt/key
-      fi
-      chown -R $RET:$RET /etc/salt/pki/minion /etc/salt/minion.d /var/log/salt/minion /var/cache/salt/minion /var/run/salt/minion
-    fi
-    if command -v systemctl; then
-        db_get salt-minion/active
-        RESLT=$(echo "$RET" | cut -d ' ' -f 1)
-        if [ "$RESLT" != 10 ]; then
-            systemctl daemon-reload
-            if [ "$RESLT" = "active" ]; then
-                systemctl restart salt-minion
-            fi
-            db_get salt-minion/enabled
-            RESLT=$(echo "$RET" | cut -d ' ' -f 1)
-            if [ "$RESLT" = "disabled" ]; then
-                systemctl disable salt-minion
-            else
-                systemctl enable salt-minion
-            fi
-        else
-            systemctl daemon-reload
-            systemctl restart salt-minion
-            systemctl enable salt-minion
+    . /usr/share/debconf/confmodule
+    if db_get salt-minion/user
+    then
+      if [ "$RET" != "root" ]; then
+        if [ ! -e "/var/log/salt/minion" ]; then
+          touch /var/log/salt/minion
+          chmod 640 /var/log/salt/minion
         fi
+        if [ ! -e "/var/log/salt/key" ]; then
+          touch /var/log/salt/key
+          chmod 640 /var/log/salt/key
+        fi
+        chown -R $RET:$RET /etc/salt/pki/minion /etc/salt/minion.d \
+                           /var/log/salt/minion /var/cache/salt/minion \
+                           /var/run/salt/minion \
+                           || true
+      fi
     fi
   ;;
+
+  abort-upgrade|abort-remove|abort-deconfigure)
+  ;;
+
+  *)
+    echo "postinst called with unknown argument '$1'" >&2
+    exit 1
+  ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
