Improve init script: specifically manage salt configurations rather than arbitrary salt processes
Unfortunately SysV init scripts tend to rummage through PIDs filtering for
appropriate processes to manage.  Unfortunately the filters are usually weak
and don't account for similar processes run by other users, PIDs of dead
processes being re-used for completely different executables, etc..  These
weaknesses can result in killing unrelated processes with potentially serious
results.

These improvements to the SysV init script is a complete rewrite with the
following improvements:

  * Specifically manage individual salt configurations rather than looking for
    salt minion-like processes.
  * Obtain salt minion information from the salt configuration - use the
    information to manage the specifically configured process.
  * Drop all of the platform-specific helper functions that allow the
    previously-mentioned weaknesses.

    + Unfortunately this means that the output information may not match the
      specific platform (this could easily be corrected).

  * Now can manage multiple salt processes started by different users

    + Unfortunately starts/stops/restarts as a group and is unable to manage
      them both as a group or as individual processes (this could easily be
      corrected)

diff --git a/pkg/rpm/salt-minion b/pkg/rpm/salt-minion
--- a/pkg/rpm/salt-minion
+++ b/pkg/rpm/salt-minion
@@ -25,8 +25,8 @@
 # processname: /usr/bin/salt-minion
 
 
-DEBIAN_VERSION=/etc/debian_version
-SUSE_RELEASE=/etc/SuSE-release
+DEBIAN_VERSION="/etc/debian_version"
+SUSE_RELEASE="/etc/SuSE-release"
 # Source function library.
 if [ -f $DEBIAN_VERSION ]; then
    break
@@ -37,120 +37,219 @@ else
 fi
 
 # Default values (can be overridden below)
-SALTMINION=/usr/bin/salt-minion
-PYTHON=/usr/bin/python
+SALTMINION="/usr/bin/salt-minion"
+SALTCALL="/usr/bin/salt-call"
+PYTHON="/usr/bin/python2.6"
+# CONFIGS are newline-separated entries of: USER CONFIG_DIR
+CONFIGS="
+root /etc/salt
+"
 MINION_ARGS=""
+TIMEOUT=30
+
+SERVICE="salt-minion"
+PROCESS="salt-minion"
 
 if [ -f /etc/default/salt ]; then
     . /etc/default/salt
+elif [ -f /etc/sysconfig/salt ]; then
+    . /etc/sysconfig/salt
 fi
-
-SERVICE=salt-minion
-PROCESS=salt-minion
 
 RETVAL=0
 
-start() {
-    echo -n $"Starting salt-minion daemon: "
-    if [ -f $SUSE_RELEASE ]; then
-        startproc -f -p /var/run/$SERVICE.pid $SALTMINION -d $MINION_ARGS
-        rc_status -v
-    elif [ -e $DEBIAN_VERSION ]; then
-        if [ -f $LOCKFILE ]; then
-            echo -n "already started, lock file found"
-            RETVAL=1
-        elif $PYTHON $SALTMINION -d $MINION_ARGS >& /dev/null; then
-            echo -n "OK"
-            RETVAL=0
-        fi
-    else
-        if [[ ! -z "$(pidofproc -p /var/run/$SERVICE.pid $PROCESS)" ]]; then
-            RETVAL=$?
-            echo -n "already running"
-        else
-            daemon --check $SERVICE $SALTMINION -d $MINION_ARGS
-            RETVAL=$?
-            [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
-            echo
-            return $RETVAL
-        fi
-    fi
-    RETVAL=$?
-    echo
-    return $RETVAL
+
+_get_pid() {
+    netstat --notrim -ap --protocol=unix | awk '$10 ~ "^'"$SOCK_DIR"'/minion_event_'"$MINION_ID_HASH"'_pub\\.ipc$" { split($9, prog, "/"); print prog[1]; }'
 }
+
+
+_is_running() {
+    [ -n "$(_get_pid)" ] && return 0 || return 1
+}
+
+
+_get_salt_config_value() {
+    "$PYTHON" "$SALTCALL" -c "$CONFIG_DIR" --no-color --local config.get "$1" | sed -r -e '$!d; s/^\s*//;'
+}
+
+
+_make_id_hash() {
+    # $1 - minion_id
+    case "$(_get_salt_config_value hash_type)" in
+	(md5) hasher="md5sum";;
+	(sha1) hasher="sha1sum";;
+	(sha224) hasher="sha224sum";;
+	(sha256) hasher="sha256sum";;
+	(sha384) hasher="sha384sum";;
+	(sha512) hasher="sha512sum";;
+    esac
+
+    printf "$1" | "$hasher" | cut -c 1-10
+}
+
+
+start() {
+    # $1 - config dir
+    local retval=0
+
+    if _is_running; then
+	echo $"Service $SERVICE:$MINION_ID already running"
+	return 1
+    fi
+
+    echo -n $"Starting $SERVICE:$MINION_ID daemon: "
+
+    "$PYTHON" "$SALTMINION" -d $MINION_ARGS >& /dev/null
+    retval=$?
+
+    _count=0
+    while ! _is_running; do
+	_count=$((_count+1))
+	sleep 1
+	if [ "$TIMEOUT" -le "$_count" ]; then
+	    echo -n "TIMEOUT "
+	    retval=1
+	    break
+	fi
+    done
+
+    if [ 0 = "$retval" ]; then
+        echo -n "OK"
+    else
+	echo -n "FAIL"
+    fi
+
+    echo
+    return $retval
+}
+
 
 stop() {
-    echo -n $"Stopping salt-minion daemon: "
-    if [ -f $SUSE_RELEASE ]; then
-        killproc -TERM $SALTMINION
-        rc_status -v
-        RETVAL=$?
-    elif [ -f $DEBIAN_VERSION ]; then
-        # Added this since Debian's start-stop-daemon doesn't support spawned processes
-        if ps -ef | grep "$PYTHON $SALTMINION" | grep -v grep | awk '{print $2}' | xargs kill &> /dev/null; then
-            echo -n "OK"
-            RETVAL=0
-        else
-            echo -n "Daemon is not started"
-            RETVAL=1
-        fi
+    # $1 - config dir
+    local retval=0
+
+    if ! _is_running; then
+	echo $"Service $SERVICE:$MINION_ID is not running"
+	return 1
+    fi
+	
+    echo -n $"Stopping $SERVICE:$MINION_ID daemon: "
+    local pid="$(_get_pid)"
+
+    kill -TERM "$pid"
+    retval=$?
+
+    _count=0
+    while _is_running; do
+	_count=$((_count+1))
+	sleep 1
+	if [ "$TIMEOUT" -le "$_count" ]; then
+	    echo -n "TIMEOUT "
+	    retval=1
+	    break
+	fi
+    done
+
+    if [ 0 = "$retval" ]; then
+        echo -n "OK"
     else
-        killproc $PROCESS
-        RETVAL=$?
-        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$SERVICE
-        # tidy up any rogue processes:
-        PROCS=`ps -ef | grep "$SALTMINION" | grep -v grep | awk '{print $2}'`
-        if [ -n "$PROCS" ]; then
-            kill $PROCS &> /dev/null
-            sleep 1
-            PROCS=`ps -ef | grep "$SALTMINION" | grep -v grep | awk '{print $2}'`
-            if [ -n "$PROCS" ]; then
-                kill -9 $PROCS &> /dev/null
-            fi
-        fi
+        echo -n "FAIL"
     fi
     echo
+
+    return $retval
 }
+
 
 restart() {
-   stop
-   start
+    # $1 - config dir
+    stop "$1"
+    start "$1"
 }
 
-# See how we were called.
-case "$1" in
-    start|stop|restart)
-        $1
-        ;;
-    status)
-        if [ -f $SUSE_RELEASE ]; then
-            echo -n "Checking for service salt-minion "
-            checkproc $SALTMINION
-            rc_status -v
-        elif [ -f $DEBIAN_VERSION ]; then
-            if [ -f $LOCKFILE ]; then
-                RETVAL=0
-                echo "salt-minion is running."
-            else
-                RETVAL=1
-                echo "salt-minion is stopped."
-            fi
-        else
-            status $PROCESS
-            RETVAL=$?
-        fi
-        ;;
-    condrestart)
-        [ -f $LOCKFILE ] && restart || :
-        ;;
-    reload)
-        echo "can't reload configuration, you have to restart it"
-        RETVAL=1
-        ;;
-    *)
+
+main() {
+    if [ -n "$DEBUG" ]; then
+	set -x
+    fi
+
+    # Pre-filter for unhandled commands
+    case "$1" in
+	(start|stop|status|restart|condrestart|reload) ;;
+	(*)
         echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
         exit 1
         ;;
-esac
-exit $RETVAL
+    esac
+
+    while read MINION_USER CONFIG_DIR; do
+	# FIXME: For now MINION_USER is unused - it should be used to
+	# start a minion as a particular user.
+
+	if [ -z "$CONFIG_DIR" ]; then
+	    continue
+	fi
+
+	if ! [ -d "$CONFIG_DIR" ]; then
+	    echo "ERROR: non-existent $SERVICE config directory: $CONFIG_DIR"
+	    RETVAL=1
+	    continue
+	fi
+
+	SOCK_DIR="$(_get_salt_config_value sock_dir)"
+	PID_FILE="$(_get_salt_config_value pidfile)"
+	MINION_ID="$(_get_salt_config_value id)"
+	MINION_ID_HASH="$(_make_id_hash "$MINION_ID")"
+	if [ \
+	    -z "$SOCK_DIR" \
+	    -o -z "$PID_FILE" \
+	    -o -z "$MINION_ID" \
+	    -o -z "$MINION_ID_HASH" \
+	  ]; then
+	    echo "ERROR: Unable to look-up config values for $CONFIG_DIR"
+	    RETVAL=1
+	fi
+
+        # See how we were called.
+	case "$1" in
+	    (start|stop|restart)
+            "$1" || RETVAL=$?
+            ;;
+	    (status)
+            _pid="$(_get_pid)"
+	    if [ -n "$_pid" ]; then
+		echo "$SERVICE:$MINION_ID is running: $_pid"
+            else
+		RETVAL=1
+		echo "$SERVICE:$MINION_ID is stopped."
+            fi
+            ;;
+	    (condrestart)
+            if _is_running; then
+		stop
+		start || RETVAL=$?
+	    fi
+	    ;;
+	    (reload)
+            echo "can't reload $SERVICE configuration - you must restart it"
+            RETVAL=1
+            ;;
+	    (*)
+            echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
+            exit 1
+            ;;
+	esac
+    done <<EOF
+$CONFIGS
+EOF
+
+    exit $RETVAL
+}
+
+
+if [ "$#" = 0 ]; then
+    main
+else
+    main "$@"
+fi
